name: navigation_time
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  device_preview: ^1.2.0
  permission_handler: ^11.3.1
  camera: ^0.11.1
  image_picker: ^1.1.2
  go_router: 14.8.0
  shared_preferences: ^2.5.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile_images/
    - assets/images/
