// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAQRjYy8Wq7qvSVcGUKK9LJ0BOWb52A8E',
    appId: '1:956020719756:web:30385756592009253e3ba9',
    messagingSenderId: '956020719756',
    projectId: 'flutter-titok-xyz',
    authDomain: 'flutter-titok-xyz.firebaseapp.com',
    storageBucket: 'flutter-titok-xyz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU3ddes_ZlY-C7CMkSAgTGeh2ZTRKrrcc',
    appId: '1:956020719756:android:c49c97d8599a0de73e3ba9',
    messagingSenderId: '956020719756',
    projectId: 'flutter-titok-xyz',
    storageBucket: 'flutter-titok-xyz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEPbpJJ941LDkjyAQS0moJDAiSSoUhac',
    appId: '1:956020719756:ios:e21230027bad78873e3ba9',
    messagingSenderId: '956020719756',
    projectId: 'flutter-titok-xyz',
    storageBucket: 'flutter-titok-xyz.firebasestorage.app',
    iosBundleId: 'com.example.navigationTime',
  );

}